//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.42
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LateBindingHelper {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LateBindingHelper.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provide a valid Automation object.
        /// </summary>
        internal static string INVALID_OBJECT {
            get {
                return ResourceManager.GetString("INVALID_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automation call failed.
        /// </summary>
        internal static string LATEBINDING_CALL_FAILED {
            get {
                return ResourceManager.GetString("LATEBINDING_CALL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter an operation to be called.
        /// </summary>
        internal static string LATEBINDING_EMPTY_CALL_STRING {
            get {
                return ResourceManager.GetString("LATEBINDING_EMPTY_CALL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Array length is different from args length.
        /// </summary>
        internal static string LATEBINDING_MISMATCHING_ARGS_AND_REFERENCE_ARRAYS {
            get {
                return ResourceManager.GetString("LATEBINDING_MISMATCHING_ARGS_AND_REFERENCE_ARRAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Automation object instance not set.
        /// </summary>
        internal static string LATEBINDING_OBJECT_NOT_SET {
            get {
                return ResourceManager.GetString("LATEBINDING_OBJECT_NOT_SET", resourceCulture);
            }
        }
    }
}
