using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("LateBindingHelper")]
[assembly: AssemblyDescriptionAttribute("A simple library for simplifying late binding calls in C#")]
[assembly: AssemblyConfigurationAttribute("release")]
[assembly: AssemblyCompanyAttribute("RickyAH")]
[assembly: AssemblyProductAttribute("LateBindingHelper")]
[assembly: AssemblyCopyrightAttribute("(C) 2008")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: GuidAttribute("47f666b9-fa01-4b03-acf9-3b583d440f0f")]
[assembly: AssemblyVersionAttribute("2.1.17.6508")]

