using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3053
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitle("LateBindingHelper")]
[assembly: AssemblyDescription("A simple library for simplifying late binding calls in C#")]
[assembly: AssemblyConfiguration("debug")]
[assembly: AssemblyCompany("RickyAH")]
[assembly: AssemblyProduct("LateBindingHelper")]
[assembly: AssemblyCopyright("(C) 2008")]
[assembly: AssemblyTrademark("")]
[assembly: Guid("47f666b9-fa01-4b03-acf9-3b583d440f0f")]
[assembly: AssemblyVersion("2.3.18.4617")]